name = "test_path"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["test_path"]

[[depends-on]]
codesearch = "*"

[[pins]]
codesearch = { path='..' }

[build-profiles]
"*" = "development"
