name = "codesearch"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["codesearch", "build_index", "fill_blobstore"]

[[depends-on]]
sqlite3 = "^3.42.0"
uri_mime = "^1.4.0"
aaa = "~0.2.6"
resources = "~0.1.0"
hex_format = "~0.1.0"
libkeccak = "^3.0.0"
libadalang = "^24"

[build-switches]
release.optimization = ["-gnatn2", "-march=native", "-O3"]

[[pins]]
sqlite3 = { url='https://github.com/JeremyGrosser/sqlite3_binding.git' }
