name = "codesearch"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["codesearch", "build_index"]

[[depends-on]]
sqlite3 = "^3.42.0"
uri_mime = "^1.4.0"
aaa = "~0.2.6"
resources = "~0.1.0"
hex_format = "~0.1.0"
libkeccak = "^3.0.0"

[build-switches]
release.optimization = ["-gnatn2", "-march=native", "-O3"]

[[pins]]
sqlite3 = { url='https://github.com/JeremyGrosser/sqlite3_binding.git' }

[gpr-set-externals]
SQLITE3_BINDING_SWITCHES = """
-DSQLITE_DQS=0
-DSQLITE_THREADSAFE=0
-DSQLITE_DEFAULT_MEMSTATUS=0
-DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
-DSQLITE_LIKE_DOESNT_MATCH_BLOBS
-DSQLITE_MAX_EXPR_DEPTH=0
-DSQLITE_OMIT_DECLTYPE
-DSQLITE_OMIT_DEPRECATED
-DSQLITE_OMIT_PROGRESS_CALLBACK
-DSQLITE_OMIT_SHARED_CACHE
-DSQLITE_USE_ALLOCA
-DSQLITE_OMIT_AUTOINIT
-DSQLITE_STRICT_SUBTYPE=1
-DSQLITE_ENABLE_FTS5
"""
